### PR TITLE
Pca

### PR DESCRIPTION
**Pull request by lennart-g**
Contains successfully tested PCA function
removed redundancy in main.py while loading and calling knn
should be merged so plot branch can build on it

### CODE REVIEW

**Review by SakulV — APPROVED** [review]

**Review by SakulV — APPROVED** [review]

**Review by npeschke — APPROVED** [review]
Just a little tip, try to keep changes to files like knn limited to their respective branches to circumvent future merge conflicts

**Comment by lennart-g** [comment]
> Just a little tip, try to keep changes to files like knn limited to their respective branches to circumvent future merge conflicts

Both the pca and the image_as_object branch were built on the same (and latest) version of the master branch so I thought merging them beforehand would prevent later conflicts when merging the image_as_object branch with a more recent version of the master branch.
And merging should go faster because we need those 5 approvals once and not twice.

And it seems that I can't approve my pull request because I'm a collaborator (probably same for yardenko) - please fix

**Comment by npeschke** [comment]
> And it seems that I can't approve my pull request because I'm a collaborator (probably same for yardenko) - please fix

Switched to 4 reviewers instead of 5

**Review by ChrisHeideb — APPROVED** [review]

**Comment by yardenko** [comment]
I can't approve as i am the collaborator, please switch to 3  reviewers.

**Comment by npeschke** [comment]
> I can't approve as i am the collaborator, please switch to 3 reviewers.

Fixed, you can now perform the merge

**Pull request merged**
